version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ./zookeeper/data:/var/lib/zookeeper/data
      - ./zookeeper/log:/var/lib/zookeeper/log
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 1
    ports:
      - "9092:9092"
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto
    ports:
      - "1883:1883" # Non-TLS MQTT
      - "9001:9001" # WebSockets (if you plan to use it later)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  mqtt-kafka-connector:
    build: ./mqtt-kafka-connector
    container_name: mqtt-kafka-connector
    depends_on:
      - kafka
      - mosquitto
    volumes:
      - ./mqtt-kafka-connector:/app
    restart: unless-stopped

  factory:
    build: ../edge/factory
    container_name: factory
    depends_on:
      - mosquitto
    volumes:
      - ../../data:/data
      - ../edge/factory:/app
    restart: unless-stopped

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "5000:5000"
    volumes:
      - ./dashboard:/app
    depends_on:
      - kafka
    restart: unless-stopped
